/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TcgManagerRouteImport } from './routes/tcg-manager'
import { Route as StoresRouteImport } from './routes/stores'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SessionsRouteImport } from './routes/sessions'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as OrganizerRouteImport } from './routes/organizer'
import { Route as MyStatsRouteImport } from './routes/my-stats'
import { Route as MetaRouteImport } from './routes/meta'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CheckInboxRouteImport } from './routes/check-inbox'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TcgManagerIndexRouteImport } from './routes/tcg-manager.index'
import { Route as StoresIndexRouteImport } from './routes/stores.index'
import { Route as SessionsIndexRouteImport } from './routes/sessions.index'
import { Route as OrganizerIndexRouteImport } from './routes/organizer.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as TournamentsIdRouteImport } from './routes/tournaments.$id'
import { Route as TcgManagerUploadRouteImport } from './routes/tcg-manager.upload'
import { Route as TcgManagerTournamentsPanelRouteImport } from './routes/tcg-manager.tournaments-panel'
import { Route as TcgManagerStoresRouteImport } from './routes/tcg-manager.stores'
import { Route as TcgManagerMyHistoryRouteImport } from './routes/tcg-manager.my-history'
import { Route as TcgManagerHistoryRouteImport } from './routes/tcg-manager.history'
import { Route as TcgManagerCalendarRouteImport } from './routes/tcg-manager.calendar'
import { Route as TcgManagerApprovedRouteImport } from './routes/tcg-manager.approved'
import { Route as TcgManagerAnalyticsRouteImport } from './routes/tcg-manager.analytics'
import { Route as StoresSlugRouteImport } from './routes/stores.$slug'
import { Route as SessionsSessionIdRouteImport } from './routes/sessions.$sessionId'
import { Route as PlayersPlayerTagRouteImport } from './routes/players.$playerTag'
import { Route as OrganizerTournamentsRouteImport } from './routes/organizer.tournaments'
import { Route as OrganizerStoreRouteImport } from './routes/organizer.store'
import { Route as OrganizerPlayersRouteImport } from './routes/organizer.players'
import { Route as OrganizerNewRouteImport } from './routes/organizer.new'
import { Route as OrganizerLeaguesRouteImport } from './routes/organizer.leagues'
import { Route as OrganizerHistoryRouteImport } from './routes/organizer.history'
import { Route as OrganizerCalendarRouteImport } from './routes/organizer.calendar'
import { Route as OrganizerAppealsRouteImport } from './routes/organizer.appeals'
import { Route as DocsFeaturesRouteImport } from './routes/docs.features'
import { Route as AdminUploadRouteImport } from './routes/admin.upload'
import { Route as AdminTournamentsPanelRouteImport } from './routes/admin.tournaments-panel'
import { Route as AdminStoresRouteImport } from './routes/admin.stores'
import { Route as AdminSeasonsRouteImport } from './routes/admin.seasons'
import { Route as AdminPublishRouteImport } from './routes/admin.publish'
import { Route as AdminPlayersRouteImport } from './routes/admin.players'
import { Route as AdminHistoryRouteImport } from './routes/admin.history'
import { Route as AdminCalendarRouteImport } from './routes/admin.calendar'
import { Route as AdminApprovedRouteImport } from './routes/admin.approved'
import { Route as AdminAdsRouteImport } from './routes/admin.ads'
import { Route as AdminActivityRouteImport } from './routes/admin.activity'
import { Route as TcgManagerTournamentsIdRouteImport } from './routes/tcg-manager.tournaments.$id'
import { Route as SessionsTournamentTournamentIdRouteImport } from './routes/sessions.tournament.$tournamentId'
import { Route as PlayersPlayerTagAchievementsRouteImport } from './routes/players.$playerTag_.achievements'
import { Route as OrganizerTournamentsIdRouteImport } from './routes/organizer.tournaments.$id'
import { Route as OrganizerLeaguesLeagueIdRouteImport } from './routes/organizer.leagues_.$leagueId'
import { Route as AdminTournamentsIdRouteImport } from './routes/admin.tournaments.$id'
import { Route as AdminPlayersIdRouteImport } from './routes/admin.players.$id'
import { Route as PlayersPlayerTagSeasonSeasonIdRouteImport } from './routes/players.$playerTag_.season.$seasonId'

const TcgManagerRoute = TcgManagerRouteImport.update({
  id: '/tcg-manager',
  path: '/tcg-manager',
  getParentRoute: () => rootRouteImport,
} as any)
const StoresRoute = StoresRouteImport.update({
  id: '/stores',
  path: '/stores',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsRoute = SessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizerRoute = OrganizerRouteImport.update({
  id: '/organizer',
  path: '/organizer',
  getParentRoute: () => rootRouteImport,
} as any)
const MyStatsRoute = MyStatsRouteImport.update({
  id: '/my-stats',
  path: '/my-stats',
  getParentRoute: () => rootRouteImport,
} as any)
const MetaRoute = MetaRouteImport.update({
  id: '/meta',
  path: '/meta',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckInboxRoute = CheckInboxRouteImport.update({
  id: '/check-inbox',
  path: '/check-inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TcgManagerIndexRoute = TcgManagerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TcgManagerRoute,
} as any)
const StoresIndexRoute = StoresIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StoresRoute,
} as any)
const SessionsIndexRoute = SessionsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SessionsRoute,
} as any)
const OrganizerIndexRoute = OrganizerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OrganizerRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const TournamentsIdRoute = TournamentsIdRouteImport.update({
  id: '/tournaments/$id',
  path: '/tournaments/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const TcgManagerUploadRoute = TcgManagerUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => TcgManagerRoute,
} as any)
const TcgManagerTournamentsPanelRoute =
  TcgManagerTournamentsPanelRouteImport.update({
    id: '/tournaments-panel',
    path: '/tournaments-panel',
    getParentRoute: () => TcgManagerRoute,
  } as any)
const TcgManagerStoresRoute = TcgManagerStoresRouteImport.update({
  id: '/stores',
  path: '/stores',
  getParentRoute: () => TcgManagerRoute,
} as any)
const TcgManagerMyHistoryRoute = TcgManagerMyHistoryRouteImport.update({
  id: '/my-history',
  path: '/my-history',
  getParentRoute: () => TcgManagerRoute,
} as any)
const TcgManagerHistoryRoute = TcgManagerHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => TcgManagerRoute,
} as any)
const TcgManagerCalendarRoute = TcgManagerCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => TcgManagerRoute,
} as any)
const TcgManagerApprovedRoute = TcgManagerApprovedRouteImport.update({
  id: '/approved',
  path: '/approved',
  getParentRoute: () => TcgManagerRoute,
} as any)
const TcgManagerAnalyticsRoute = TcgManagerAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => TcgManagerRoute,
} as any)
const StoresSlugRoute = StoresSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => StoresRoute,
} as any)
const SessionsSessionIdRoute = SessionsSessionIdRouteImport.update({
  id: '/$sessionId',
  path: '/$sessionId',
  getParentRoute: () => SessionsRoute,
} as any)
const PlayersPlayerTagRoute = PlayersPlayerTagRouteImport.update({
  id: '/players/$playerTag',
  path: '/players/$playerTag',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizerTournamentsRoute = OrganizerTournamentsRouteImport.update({
  id: '/tournaments',
  path: '/tournaments',
  getParentRoute: () => OrganizerRoute,
} as any)
const OrganizerStoreRoute = OrganizerStoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => OrganizerRoute,
} as any)
const OrganizerPlayersRoute = OrganizerPlayersRouteImport.update({
  id: '/players',
  path: '/players',
  getParentRoute: () => OrganizerRoute,
} as any)
const OrganizerNewRoute = OrganizerNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => OrganizerRoute,
} as any)
const OrganizerLeaguesRoute = OrganizerLeaguesRouteImport.update({
  id: '/leagues',
  path: '/leagues',
  getParentRoute: () => OrganizerRoute,
} as any)
const OrganizerHistoryRoute = OrganizerHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => OrganizerRoute,
} as any)
const OrganizerCalendarRoute = OrganizerCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => OrganizerRoute,
} as any)
const OrganizerAppealsRoute = OrganizerAppealsRouteImport.update({
  id: '/appeals',
  path: '/appeals',
  getParentRoute: () => OrganizerRoute,
} as any)
const DocsFeaturesRoute = DocsFeaturesRouteImport.update({
  id: '/docs/features',
  path: '/docs/features',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUploadRoute = AdminUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTournamentsPanelRoute = AdminTournamentsPanelRouteImport.update({
  id: '/tournaments-panel',
  path: '/tournaments-panel',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStoresRoute = AdminStoresRouteImport.update({
  id: '/stores',
  path: '/stores',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSeasonsRoute = AdminSeasonsRouteImport.update({
  id: '/seasons',
  path: '/seasons',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPublishRoute = AdminPublishRouteImport.update({
  id: '/publish',
  path: '/publish',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPlayersRoute = AdminPlayersRouteImport.update({
  id: '/players',
  path: '/players',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHistoryRoute = AdminHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCalendarRoute = AdminCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AdminRoute,
} as any)
const AdminApprovedRoute = AdminApprovedRouteImport.update({
  id: '/approved',
  path: '/approved',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdsRoute = AdminAdsRouteImport.update({
  id: '/ads',
  path: '/ads',
  getParentRoute: () => AdminRoute,
} as any)
const AdminActivityRoute = AdminActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AdminRoute,
} as any)
const TcgManagerTournamentsIdRoute = TcgManagerTournamentsIdRouteImport.update({
  id: '/tournaments/$id',
  path: '/tournaments/$id',
  getParentRoute: () => TcgManagerRoute,
} as any)
const SessionsTournamentTournamentIdRoute =
  SessionsTournamentTournamentIdRouteImport.update({
    id: '/tournament/$tournamentId',
    path: '/tournament/$tournamentId',
    getParentRoute: () => SessionsRoute,
  } as any)
const PlayersPlayerTagAchievementsRoute =
  PlayersPlayerTagAchievementsRouteImport.update({
    id: '/players/$playerTag_/achievements',
    path: '/players/$playerTag/achievements',
    getParentRoute: () => rootRouteImport,
  } as any)
const OrganizerTournamentsIdRoute = OrganizerTournamentsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => OrganizerTournamentsRoute,
} as any)
const OrganizerLeaguesLeagueIdRoute =
  OrganizerLeaguesLeagueIdRouteImport.update({
    id: '/leagues_/$leagueId',
    path: '/leagues/$leagueId',
    getParentRoute: () => OrganizerRoute,
  } as any)
const AdminTournamentsIdRoute = AdminTournamentsIdRouteImport.update({
  id: '/tournaments/$id',
  path: '/tournaments/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPlayersIdRoute = AdminPlayersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminPlayersRoute,
} as any)
const PlayersPlayerTagSeasonSeasonIdRoute =
  PlayersPlayerTagSeasonSeasonIdRouteImport.update({
    id: '/players/$playerTag_/season/$seasonId',
    path: '/players/$playerTag/season/$seasonId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/calendar': typeof CalendarRoute
  '/check-inbox': typeof CheckInboxRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/meta': typeof MetaRoute
  '/my-stats': typeof MyStatsRoute
  '/organizer': typeof OrganizerRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/sessions': typeof SessionsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/stores': typeof StoresRouteWithChildren
  '/tcg-manager': typeof TcgManagerRouteWithChildren
  '/admin/activity': typeof AdminActivityRoute
  '/admin/ads': typeof AdminAdsRoute
  '/admin/approved': typeof AdminApprovedRoute
  '/admin/calendar': typeof AdminCalendarRoute
  '/admin/history': typeof AdminHistoryRoute
  '/admin/players': typeof AdminPlayersRouteWithChildren
  '/admin/publish': typeof AdminPublishRoute
  '/admin/seasons': typeof AdminSeasonsRoute
  '/admin/stores': typeof AdminStoresRoute
  '/admin/tournaments-panel': typeof AdminTournamentsPanelRoute
  '/admin/upload': typeof AdminUploadRoute
  '/docs/features': typeof DocsFeaturesRoute
  '/organizer/appeals': typeof OrganizerAppealsRoute
  '/organizer/calendar': typeof OrganizerCalendarRoute
  '/organizer/history': typeof OrganizerHistoryRoute
  '/organizer/leagues': typeof OrganizerLeaguesRoute
  '/organizer/new': typeof OrganizerNewRoute
  '/organizer/players': typeof OrganizerPlayersRoute
  '/organizer/store': typeof OrganizerStoreRoute
  '/organizer/tournaments': typeof OrganizerTournamentsRouteWithChildren
  '/players/$playerTag': typeof PlayersPlayerTagRoute
  '/sessions/$sessionId': typeof SessionsSessionIdRoute
  '/stores/$slug': typeof StoresSlugRoute
  '/tcg-manager/analytics': typeof TcgManagerAnalyticsRoute
  '/tcg-manager/approved': typeof TcgManagerApprovedRoute
  '/tcg-manager/calendar': typeof TcgManagerCalendarRoute
  '/tcg-manager/history': typeof TcgManagerHistoryRoute
  '/tcg-manager/my-history': typeof TcgManagerMyHistoryRoute
  '/tcg-manager/stores': typeof TcgManagerStoresRoute
  '/tcg-manager/tournaments-panel': typeof TcgManagerTournamentsPanelRoute
  '/tcg-manager/upload': typeof TcgManagerUploadRoute
  '/tournaments/$id': typeof TournamentsIdRoute
  '/admin/': typeof AdminIndexRoute
  '/organizer/': typeof OrganizerIndexRoute
  '/sessions/': typeof SessionsIndexRoute
  '/stores/': typeof StoresIndexRoute
  '/tcg-manager/': typeof TcgManagerIndexRoute
  '/admin/players/$id': typeof AdminPlayersIdRoute
  '/admin/tournaments/$id': typeof AdminTournamentsIdRoute
  '/organizer/leagues/$leagueId': typeof OrganizerLeaguesLeagueIdRoute
  '/organizer/tournaments/$id': typeof OrganizerTournamentsIdRoute
  '/players/$playerTag/achievements': typeof PlayersPlayerTagAchievementsRoute
  '/sessions/tournament/$tournamentId': typeof SessionsTournamentTournamentIdRoute
  '/tcg-manager/tournaments/$id': typeof TcgManagerTournamentsIdRoute
  '/players/$playerTag/season/$seasonId': typeof PlayersPlayerTagSeasonSeasonIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/check-inbox': typeof CheckInboxRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/meta': typeof MetaRoute
  '/my-stats': typeof MyStatsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/admin/activity': typeof AdminActivityRoute
  '/admin/ads': typeof AdminAdsRoute
  '/admin/approved': typeof AdminApprovedRoute
  '/admin/calendar': typeof AdminCalendarRoute
  '/admin/history': typeof AdminHistoryRoute
  '/admin/players': typeof AdminPlayersRouteWithChildren
  '/admin/publish': typeof AdminPublishRoute
  '/admin/seasons': typeof AdminSeasonsRoute
  '/admin/stores': typeof AdminStoresRoute
  '/admin/tournaments-panel': typeof AdminTournamentsPanelRoute
  '/admin/upload': typeof AdminUploadRoute
  '/docs/features': typeof DocsFeaturesRoute
  '/organizer/appeals': typeof OrganizerAppealsRoute
  '/organizer/calendar': typeof OrganizerCalendarRoute
  '/organizer/history': typeof OrganizerHistoryRoute
  '/organizer/leagues': typeof OrganizerLeaguesRoute
  '/organizer/new': typeof OrganizerNewRoute
  '/organizer/players': typeof OrganizerPlayersRoute
  '/organizer/store': typeof OrganizerStoreRoute
  '/organizer/tournaments': typeof OrganizerTournamentsRouteWithChildren
  '/players/$playerTag': typeof PlayersPlayerTagRoute
  '/sessions/$sessionId': typeof SessionsSessionIdRoute
  '/stores/$slug': typeof StoresSlugRoute
  '/tcg-manager/analytics': typeof TcgManagerAnalyticsRoute
  '/tcg-manager/approved': typeof TcgManagerApprovedRoute
  '/tcg-manager/calendar': typeof TcgManagerCalendarRoute
  '/tcg-manager/history': typeof TcgManagerHistoryRoute
  '/tcg-manager/my-history': typeof TcgManagerMyHistoryRoute
  '/tcg-manager/stores': typeof TcgManagerStoresRoute
  '/tcg-manager/tournaments-panel': typeof TcgManagerTournamentsPanelRoute
  '/tcg-manager/upload': typeof TcgManagerUploadRoute
  '/tournaments/$id': typeof TournamentsIdRoute
  '/admin': typeof AdminIndexRoute
  '/organizer': typeof OrganizerIndexRoute
  '/sessions': typeof SessionsIndexRoute
  '/stores': typeof StoresIndexRoute
  '/tcg-manager': typeof TcgManagerIndexRoute
  '/admin/players/$id': typeof AdminPlayersIdRoute
  '/admin/tournaments/$id': typeof AdminTournamentsIdRoute
  '/organizer/leagues/$leagueId': typeof OrganizerLeaguesLeagueIdRoute
  '/organizer/tournaments/$id': typeof OrganizerTournamentsIdRoute
  '/players/$playerTag/achievements': typeof PlayersPlayerTagAchievementsRoute
  '/sessions/tournament/$tournamentId': typeof SessionsTournamentTournamentIdRoute
  '/tcg-manager/tournaments/$id': typeof TcgManagerTournamentsIdRoute
  '/players/$playerTag/season/$seasonId': typeof PlayersPlayerTagSeasonSeasonIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/calendar': typeof CalendarRoute
  '/check-inbox': typeof CheckInboxRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/meta': typeof MetaRoute
  '/my-stats': typeof MyStatsRoute
  '/organizer': typeof OrganizerRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/sessions': typeof SessionsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/stores': typeof StoresRouteWithChildren
  '/tcg-manager': typeof TcgManagerRouteWithChildren
  '/admin/activity': typeof AdminActivityRoute
  '/admin/ads': typeof AdminAdsRoute
  '/admin/approved': typeof AdminApprovedRoute
  '/admin/calendar': typeof AdminCalendarRoute
  '/admin/history': typeof AdminHistoryRoute
  '/admin/players': typeof AdminPlayersRouteWithChildren
  '/admin/publish': typeof AdminPublishRoute
  '/admin/seasons': typeof AdminSeasonsRoute
  '/admin/stores': typeof AdminStoresRoute
  '/admin/tournaments-panel': typeof AdminTournamentsPanelRoute
  '/admin/upload': typeof AdminUploadRoute
  '/docs/features': typeof DocsFeaturesRoute
  '/organizer/appeals': typeof OrganizerAppealsRoute
  '/organizer/calendar': typeof OrganizerCalendarRoute
  '/organizer/history': typeof OrganizerHistoryRoute
  '/organizer/leagues': typeof OrganizerLeaguesRoute
  '/organizer/new': typeof OrganizerNewRoute
  '/organizer/players': typeof OrganizerPlayersRoute
  '/organizer/store': typeof OrganizerStoreRoute
  '/organizer/tournaments': typeof OrganizerTournamentsRouteWithChildren
  '/players/$playerTag': typeof PlayersPlayerTagRoute
  '/sessions/$sessionId': typeof SessionsSessionIdRoute
  '/stores/$slug': typeof StoresSlugRoute
  '/tcg-manager/analytics': typeof TcgManagerAnalyticsRoute
  '/tcg-manager/approved': typeof TcgManagerApprovedRoute
  '/tcg-manager/calendar': typeof TcgManagerCalendarRoute
  '/tcg-manager/history': typeof TcgManagerHistoryRoute
  '/tcg-manager/my-history': typeof TcgManagerMyHistoryRoute
  '/tcg-manager/stores': typeof TcgManagerStoresRoute
  '/tcg-manager/tournaments-panel': typeof TcgManagerTournamentsPanelRoute
  '/tcg-manager/upload': typeof TcgManagerUploadRoute
  '/tournaments/$id': typeof TournamentsIdRoute
  '/admin/': typeof AdminIndexRoute
  '/organizer/': typeof OrganizerIndexRoute
  '/sessions/': typeof SessionsIndexRoute
  '/stores/': typeof StoresIndexRoute
  '/tcg-manager/': typeof TcgManagerIndexRoute
  '/admin/players/$id': typeof AdminPlayersIdRoute
  '/admin/tournaments/$id': typeof AdminTournamentsIdRoute
  '/organizer/leagues_/$leagueId': typeof OrganizerLeaguesLeagueIdRoute
  '/organizer/tournaments/$id': typeof OrganizerTournamentsIdRoute
  '/players/$playerTag_/achievements': typeof PlayersPlayerTagAchievementsRoute
  '/sessions/tournament/$tournamentId': typeof SessionsTournamentTournamentIdRoute
  '/tcg-manager/tournaments/$id': typeof TcgManagerTournamentsIdRoute
  '/players/$playerTag_/season/$seasonId': typeof PlayersPlayerTagSeasonSeasonIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/calendar'
    | '/check-inbox'
    | '/dashboard'
    | '/login'
    | '/meta'
    | '/my-stats'
    | '/organizer'
    | '/reset-password'
    | '/sessions'
    | '/settings'
    | '/signup'
    | '/stores'
    | '/tcg-manager'
    | '/admin/activity'
    | '/admin/ads'
    | '/admin/approved'
    | '/admin/calendar'
    | '/admin/history'
    | '/admin/players'
    | '/admin/publish'
    | '/admin/seasons'
    | '/admin/stores'
    | '/admin/tournaments-panel'
    | '/admin/upload'
    | '/docs/features'
    | '/organizer/appeals'
    | '/organizer/calendar'
    | '/organizer/history'
    | '/organizer/leagues'
    | '/organizer/new'
    | '/organizer/players'
    | '/organizer/store'
    | '/organizer/tournaments'
    | '/players/$playerTag'
    | '/sessions/$sessionId'
    | '/stores/$slug'
    | '/tcg-manager/analytics'
    | '/tcg-manager/approved'
    | '/tcg-manager/calendar'
    | '/tcg-manager/history'
    | '/tcg-manager/my-history'
    | '/tcg-manager/stores'
    | '/tcg-manager/tournaments-panel'
    | '/tcg-manager/upload'
    | '/tournaments/$id'
    | '/admin/'
    | '/organizer/'
    | '/sessions/'
    | '/stores/'
    | '/tcg-manager/'
    | '/admin/players/$id'
    | '/admin/tournaments/$id'
    | '/organizer/leagues/$leagueId'
    | '/organizer/tournaments/$id'
    | '/players/$playerTag/achievements'
    | '/sessions/tournament/$tournamentId'
    | '/tcg-manager/tournaments/$id'
    | '/players/$playerTag/season/$seasonId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calendar'
    | '/check-inbox'
    | '/dashboard'
    | '/login'
    | '/meta'
    | '/my-stats'
    | '/reset-password'
    | '/settings'
    | '/signup'
    | '/admin/activity'
    | '/admin/ads'
    | '/admin/approved'
    | '/admin/calendar'
    | '/admin/history'
    | '/admin/players'
    | '/admin/publish'
    | '/admin/seasons'
    | '/admin/stores'
    | '/admin/tournaments-panel'
    | '/admin/upload'
    | '/docs/features'
    | '/organizer/appeals'
    | '/organizer/calendar'
    | '/organizer/history'
    | '/organizer/leagues'
    | '/organizer/new'
    | '/organizer/players'
    | '/organizer/store'
    | '/organizer/tournaments'
    | '/players/$playerTag'
    | '/sessions/$sessionId'
    | '/stores/$slug'
    | '/tcg-manager/analytics'
    | '/tcg-manager/approved'
    | '/tcg-manager/calendar'
    | '/tcg-manager/history'
    | '/tcg-manager/my-history'
    | '/tcg-manager/stores'
    | '/tcg-manager/tournaments-panel'
    | '/tcg-manager/upload'
    | '/tournaments/$id'
    | '/admin'
    | '/organizer'
    | '/sessions'
    | '/stores'
    | '/tcg-manager'
    | '/admin/players/$id'
    | '/admin/tournaments/$id'
    | '/organizer/leagues/$leagueId'
    | '/organizer/tournaments/$id'
    | '/players/$playerTag/achievements'
    | '/sessions/tournament/$tournamentId'
    | '/tcg-manager/tournaments/$id'
    | '/players/$playerTag/season/$seasonId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/calendar'
    | '/check-inbox'
    | '/dashboard'
    | '/login'
    | '/meta'
    | '/my-stats'
    | '/organizer'
    | '/reset-password'
    | '/sessions'
    | '/settings'
    | '/signup'
    | '/stores'
    | '/tcg-manager'
    | '/admin/activity'
    | '/admin/ads'
    | '/admin/approved'
    | '/admin/calendar'
    | '/admin/history'
    | '/admin/players'
    | '/admin/publish'
    | '/admin/seasons'
    | '/admin/stores'
    | '/admin/tournaments-panel'
    | '/admin/upload'
    | '/docs/features'
    | '/organizer/appeals'
    | '/organizer/calendar'
    | '/organizer/history'
    | '/organizer/leagues'
    | '/organizer/new'
    | '/organizer/players'
    | '/organizer/store'
    | '/organizer/tournaments'
    | '/players/$playerTag'
    | '/sessions/$sessionId'
    | '/stores/$slug'
    | '/tcg-manager/analytics'
    | '/tcg-manager/approved'
    | '/tcg-manager/calendar'
    | '/tcg-manager/history'
    | '/tcg-manager/my-history'
    | '/tcg-manager/stores'
    | '/tcg-manager/tournaments-panel'
    | '/tcg-manager/upload'
    | '/tournaments/$id'
    | '/admin/'
    | '/organizer/'
    | '/sessions/'
    | '/stores/'
    | '/tcg-manager/'
    | '/admin/players/$id'
    | '/admin/tournaments/$id'
    | '/organizer/leagues_/$leagueId'
    | '/organizer/tournaments/$id'
    | '/players/$playerTag_/achievements'
    | '/sessions/tournament/$tournamentId'
    | '/tcg-manager/tournaments/$id'
    | '/players/$playerTag_/season/$seasonId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CalendarRoute: typeof CalendarRoute
  CheckInboxRoute: typeof CheckInboxRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  MetaRoute: typeof MetaRoute
  MyStatsRoute: typeof MyStatsRoute
  OrganizerRoute: typeof OrganizerRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
  SessionsRoute: typeof SessionsRouteWithChildren
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  StoresRoute: typeof StoresRouteWithChildren
  TcgManagerRoute: typeof TcgManagerRouteWithChildren
  DocsFeaturesRoute: typeof DocsFeaturesRoute
  PlayersPlayerTagRoute: typeof PlayersPlayerTagRoute
  TournamentsIdRoute: typeof TournamentsIdRoute
  PlayersPlayerTagAchievementsRoute: typeof PlayersPlayerTagAchievementsRoute
  PlayersPlayerTagSeasonSeasonIdRoute: typeof PlayersPlayerTagSeasonSeasonIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tcg-manager': {
      id: '/tcg-manager'
      path: '/tcg-manager'
      fullPath: '/tcg-manager'
      preLoaderRoute: typeof TcgManagerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stores': {
      id: '/stores'
      path: '/stores'
      fullPath: '/stores'
      preLoaderRoute: typeof StoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions': {
      id: '/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof SessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizer': {
      id: '/organizer'
      path: '/organizer'
      fullPath: '/organizer'
      preLoaderRoute: typeof OrganizerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-stats': {
      id: '/my-stats'
      path: '/my-stats'
      fullPath: '/my-stats'
      preLoaderRoute: typeof MyStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meta': {
      id: '/meta'
      path: '/meta'
      fullPath: '/meta'
      preLoaderRoute: typeof MetaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/check-inbox': {
      id: '/check-inbox'
      path: '/check-inbox'
      fullPath: '/check-inbox'
      preLoaderRoute: typeof CheckInboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tcg-manager/': {
      id: '/tcg-manager/'
      path: '/'
      fullPath: '/tcg-manager/'
      preLoaderRoute: typeof TcgManagerIndexRouteImport
      parentRoute: typeof TcgManagerRoute
    }
    '/stores/': {
      id: '/stores/'
      path: '/'
      fullPath: '/stores/'
      preLoaderRoute: typeof StoresIndexRouteImport
      parentRoute: typeof StoresRoute
    }
    '/sessions/': {
      id: '/sessions/'
      path: '/'
      fullPath: '/sessions/'
      preLoaderRoute: typeof SessionsIndexRouteImport
      parentRoute: typeof SessionsRoute
    }
    '/organizer/': {
      id: '/organizer/'
      path: '/'
      fullPath: '/organizer/'
      preLoaderRoute: typeof OrganizerIndexRouteImport
      parentRoute: typeof OrganizerRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/tournaments/$id': {
      id: '/tournaments/$id'
      path: '/tournaments/$id'
      fullPath: '/tournaments/$id'
      preLoaderRoute: typeof TournamentsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tcg-manager/upload': {
      id: '/tcg-manager/upload'
      path: '/upload'
      fullPath: '/tcg-manager/upload'
      preLoaderRoute: typeof TcgManagerUploadRouteImport
      parentRoute: typeof TcgManagerRoute
    }
    '/tcg-manager/tournaments-panel': {
      id: '/tcg-manager/tournaments-panel'
      path: '/tournaments-panel'
      fullPath: '/tcg-manager/tournaments-panel'
      preLoaderRoute: typeof TcgManagerTournamentsPanelRouteImport
      parentRoute: typeof TcgManagerRoute
    }
    '/tcg-manager/stores': {
      id: '/tcg-manager/stores'
      path: '/stores'
      fullPath: '/tcg-manager/stores'
      preLoaderRoute: typeof TcgManagerStoresRouteImport
      parentRoute: typeof TcgManagerRoute
    }
    '/tcg-manager/my-history': {
      id: '/tcg-manager/my-history'
      path: '/my-history'
      fullPath: '/tcg-manager/my-history'
      preLoaderRoute: typeof TcgManagerMyHistoryRouteImport
      parentRoute: typeof TcgManagerRoute
    }
    '/tcg-manager/history': {
      id: '/tcg-manager/history'
      path: '/history'
      fullPath: '/tcg-manager/history'
      preLoaderRoute: typeof TcgManagerHistoryRouteImport
      parentRoute: typeof TcgManagerRoute
    }
    '/tcg-manager/calendar': {
      id: '/tcg-manager/calendar'
      path: '/calendar'
      fullPath: '/tcg-manager/calendar'
      preLoaderRoute: typeof TcgManagerCalendarRouteImport
      parentRoute: typeof TcgManagerRoute
    }
    '/tcg-manager/approved': {
      id: '/tcg-manager/approved'
      path: '/approved'
      fullPath: '/tcg-manager/approved'
      preLoaderRoute: typeof TcgManagerApprovedRouteImport
      parentRoute: typeof TcgManagerRoute
    }
    '/tcg-manager/analytics': {
      id: '/tcg-manager/analytics'
      path: '/analytics'
      fullPath: '/tcg-manager/analytics'
      preLoaderRoute: typeof TcgManagerAnalyticsRouteImport
      parentRoute: typeof TcgManagerRoute
    }
    '/stores/$slug': {
      id: '/stores/$slug'
      path: '/$slug'
      fullPath: '/stores/$slug'
      preLoaderRoute: typeof StoresSlugRouteImport
      parentRoute: typeof StoresRoute
    }
    '/sessions/$sessionId': {
      id: '/sessions/$sessionId'
      path: '/$sessionId'
      fullPath: '/sessions/$sessionId'
      preLoaderRoute: typeof SessionsSessionIdRouteImport
      parentRoute: typeof SessionsRoute
    }
    '/players/$playerTag': {
      id: '/players/$playerTag'
      path: '/players/$playerTag'
      fullPath: '/players/$playerTag'
      preLoaderRoute: typeof PlayersPlayerTagRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizer/tournaments': {
      id: '/organizer/tournaments'
      path: '/tournaments'
      fullPath: '/organizer/tournaments'
      preLoaderRoute: typeof OrganizerTournamentsRouteImport
      parentRoute: typeof OrganizerRoute
    }
    '/organizer/store': {
      id: '/organizer/store'
      path: '/store'
      fullPath: '/organizer/store'
      preLoaderRoute: typeof OrganizerStoreRouteImport
      parentRoute: typeof OrganizerRoute
    }
    '/organizer/players': {
      id: '/organizer/players'
      path: '/players'
      fullPath: '/organizer/players'
      preLoaderRoute: typeof OrganizerPlayersRouteImport
      parentRoute: typeof OrganizerRoute
    }
    '/organizer/new': {
      id: '/organizer/new'
      path: '/new'
      fullPath: '/organizer/new'
      preLoaderRoute: typeof OrganizerNewRouteImport
      parentRoute: typeof OrganizerRoute
    }
    '/organizer/leagues': {
      id: '/organizer/leagues'
      path: '/leagues'
      fullPath: '/organizer/leagues'
      preLoaderRoute: typeof OrganizerLeaguesRouteImport
      parentRoute: typeof OrganizerRoute
    }
    '/organizer/history': {
      id: '/organizer/history'
      path: '/history'
      fullPath: '/organizer/history'
      preLoaderRoute: typeof OrganizerHistoryRouteImport
      parentRoute: typeof OrganizerRoute
    }
    '/organizer/calendar': {
      id: '/organizer/calendar'
      path: '/calendar'
      fullPath: '/organizer/calendar'
      preLoaderRoute: typeof OrganizerCalendarRouteImport
      parentRoute: typeof OrganizerRoute
    }
    '/organizer/appeals': {
      id: '/organizer/appeals'
      path: '/appeals'
      fullPath: '/organizer/appeals'
      preLoaderRoute: typeof OrganizerAppealsRouteImport
      parentRoute: typeof OrganizerRoute
    }
    '/docs/features': {
      id: '/docs/features'
      path: '/docs/features'
      fullPath: '/docs/features'
      preLoaderRoute: typeof DocsFeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/upload': {
      id: '/admin/upload'
      path: '/upload'
      fullPath: '/admin/upload'
      preLoaderRoute: typeof AdminUploadRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tournaments-panel': {
      id: '/admin/tournaments-panel'
      path: '/tournaments-panel'
      fullPath: '/admin/tournaments-panel'
      preLoaderRoute: typeof AdminTournamentsPanelRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/stores': {
      id: '/admin/stores'
      path: '/stores'
      fullPath: '/admin/stores'
      preLoaderRoute: typeof AdminStoresRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/seasons': {
      id: '/admin/seasons'
      path: '/seasons'
      fullPath: '/admin/seasons'
      preLoaderRoute: typeof AdminSeasonsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/publish': {
      id: '/admin/publish'
      path: '/publish'
      fullPath: '/admin/publish'
      preLoaderRoute: typeof AdminPublishRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/players': {
      id: '/admin/players'
      path: '/players'
      fullPath: '/admin/players'
      preLoaderRoute: typeof AdminPlayersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/history': {
      id: '/admin/history'
      path: '/history'
      fullPath: '/admin/history'
      preLoaderRoute: typeof AdminHistoryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/calendar': {
      id: '/admin/calendar'
      path: '/calendar'
      fullPath: '/admin/calendar'
      preLoaderRoute: typeof AdminCalendarRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/approved': {
      id: '/admin/approved'
      path: '/approved'
      fullPath: '/admin/approved'
      preLoaderRoute: typeof AdminApprovedRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ads': {
      id: '/admin/ads'
      path: '/ads'
      fullPath: '/admin/ads'
      preLoaderRoute: typeof AdminAdsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/activity': {
      id: '/admin/activity'
      path: '/activity'
      fullPath: '/admin/activity'
      preLoaderRoute: typeof AdminActivityRouteImport
      parentRoute: typeof AdminRoute
    }
    '/tcg-manager/tournaments/$id': {
      id: '/tcg-manager/tournaments/$id'
      path: '/tournaments/$id'
      fullPath: '/tcg-manager/tournaments/$id'
      preLoaderRoute: typeof TcgManagerTournamentsIdRouteImport
      parentRoute: typeof TcgManagerRoute
    }
    '/sessions/tournament/$tournamentId': {
      id: '/sessions/tournament/$tournamentId'
      path: '/tournament/$tournamentId'
      fullPath: '/sessions/tournament/$tournamentId'
      preLoaderRoute: typeof SessionsTournamentTournamentIdRouteImport
      parentRoute: typeof SessionsRoute
    }
    '/players/$playerTag_/achievements': {
      id: '/players/$playerTag_/achievements'
      path: '/players/$playerTag/achievements'
      fullPath: '/players/$playerTag/achievements'
      preLoaderRoute: typeof PlayersPlayerTagAchievementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizer/tournaments/$id': {
      id: '/organizer/tournaments/$id'
      path: '/$id'
      fullPath: '/organizer/tournaments/$id'
      preLoaderRoute: typeof OrganizerTournamentsIdRouteImport
      parentRoute: typeof OrganizerTournamentsRoute
    }
    '/organizer/leagues_/$leagueId': {
      id: '/organizer/leagues_/$leagueId'
      path: '/leagues/$leagueId'
      fullPath: '/organizer/leagues/$leagueId'
      preLoaderRoute: typeof OrganizerLeaguesLeagueIdRouteImport
      parentRoute: typeof OrganizerRoute
    }
    '/admin/tournaments/$id': {
      id: '/admin/tournaments/$id'
      path: '/tournaments/$id'
      fullPath: '/admin/tournaments/$id'
      preLoaderRoute: typeof AdminTournamentsIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/players/$id': {
      id: '/admin/players/$id'
      path: '/$id'
      fullPath: '/admin/players/$id'
      preLoaderRoute: typeof AdminPlayersIdRouteImport
      parentRoute: typeof AdminPlayersRoute
    }
    '/players/$playerTag_/season/$seasonId': {
      id: '/players/$playerTag_/season/$seasonId'
      path: '/players/$playerTag/season/$seasonId'
      fullPath: '/players/$playerTag/season/$seasonId'
      preLoaderRoute: typeof PlayersPlayerTagSeasonSeasonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminPlayersRouteChildren {
  AdminPlayersIdRoute: typeof AdminPlayersIdRoute
}

const AdminPlayersRouteChildren: AdminPlayersRouteChildren = {
  AdminPlayersIdRoute: AdminPlayersIdRoute,
}

const AdminPlayersRouteWithChildren = AdminPlayersRoute._addFileChildren(
  AdminPlayersRouteChildren,
)

interface AdminRouteChildren {
  AdminActivityRoute: typeof AdminActivityRoute
  AdminAdsRoute: typeof AdminAdsRoute
  AdminApprovedRoute: typeof AdminApprovedRoute
  AdminCalendarRoute: typeof AdminCalendarRoute
  AdminHistoryRoute: typeof AdminHistoryRoute
  AdminPlayersRoute: typeof AdminPlayersRouteWithChildren
  AdminPublishRoute: typeof AdminPublishRoute
  AdminSeasonsRoute: typeof AdminSeasonsRoute
  AdminStoresRoute: typeof AdminStoresRoute
  AdminTournamentsPanelRoute: typeof AdminTournamentsPanelRoute
  AdminUploadRoute: typeof AdminUploadRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminTournamentsIdRoute: typeof AdminTournamentsIdRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminActivityRoute: AdminActivityRoute,
  AdminAdsRoute: AdminAdsRoute,
  AdminApprovedRoute: AdminApprovedRoute,
  AdminCalendarRoute: AdminCalendarRoute,
  AdminHistoryRoute: AdminHistoryRoute,
  AdminPlayersRoute: AdminPlayersRouteWithChildren,
  AdminPublishRoute: AdminPublishRoute,
  AdminSeasonsRoute: AdminSeasonsRoute,
  AdminStoresRoute: AdminStoresRoute,
  AdminTournamentsPanelRoute: AdminTournamentsPanelRoute,
  AdminUploadRoute: AdminUploadRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminTournamentsIdRoute: AdminTournamentsIdRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface OrganizerTournamentsRouteChildren {
  OrganizerTournamentsIdRoute: typeof OrganizerTournamentsIdRoute
}

const OrganizerTournamentsRouteChildren: OrganizerTournamentsRouteChildren = {
  OrganizerTournamentsIdRoute: OrganizerTournamentsIdRoute,
}

const OrganizerTournamentsRouteWithChildren =
  OrganizerTournamentsRoute._addFileChildren(OrganizerTournamentsRouteChildren)

interface OrganizerRouteChildren {
  OrganizerAppealsRoute: typeof OrganizerAppealsRoute
  OrganizerCalendarRoute: typeof OrganizerCalendarRoute
  OrganizerHistoryRoute: typeof OrganizerHistoryRoute
  OrganizerLeaguesRoute: typeof OrganizerLeaguesRoute
  OrganizerNewRoute: typeof OrganizerNewRoute
  OrganizerPlayersRoute: typeof OrganizerPlayersRoute
  OrganizerStoreRoute: typeof OrganizerStoreRoute
  OrganizerTournamentsRoute: typeof OrganizerTournamentsRouteWithChildren
  OrganizerIndexRoute: typeof OrganizerIndexRoute
  OrganizerLeaguesLeagueIdRoute: typeof OrganizerLeaguesLeagueIdRoute
}

const OrganizerRouteChildren: OrganizerRouteChildren = {
  OrganizerAppealsRoute: OrganizerAppealsRoute,
  OrganizerCalendarRoute: OrganizerCalendarRoute,
  OrganizerHistoryRoute: OrganizerHistoryRoute,
  OrganizerLeaguesRoute: OrganizerLeaguesRoute,
  OrganizerNewRoute: OrganizerNewRoute,
  OrganizerPlayersRoute: OrganizerPlayersRoute,
  OrganizerStoreRoute: OrganizerStoreRoute,
  OrganizerTournamentsRoute: OrganizerTournamentsRouteWithChildren,
  OrganizerIndexRoute: OrganizerIndexRoute,
  OrganizerLeaguesLeagueIdRoute: OrganizerLeaguesLeagueIdRoute,
}

const OrganizerRouteWithChildren = OrganizerRoute._addFileChildren(
  OrganizerRouteChildren,
)

interface SessionsRouteChildren {
  SessionsSessionIdRoute: typeof SessionsSessionIdRoute
  SessionsIndexRoute: typeof SessionsIndexRoute
  SessionsTournamentTournamentIdRoute: typeof SessionsTournamentTournamentIdRoute
}

const SessionsRouteChildren: SessionsRouteChildren = {
  SessionsSessionIdRoute: SessionsSessionIdRoute,
  SessionsIndexRoute: SessionsIndexRoute,
  SessionsTournamentTournamentIdRoute: SessionsTournamentTournamentIdRoute,
}

const SessionsRouteWithChildren = SessionsRoute._addFileChildren(
  SessionsRouteChildren,
)

interface StoresRouteChildren {
  StoresSlugRoute: typeof StoresSlugRoute
  StoresIndexRoute: typeof StoresIndexRoute
}

const StoresRouteChildren: StoresRouteChildren = {
  StoresSlugRoute: StoresSlugRoute,
  StoresIndexRoute: StoresIndexRoute,
}

const StoresRouteWithChildren =
  StoresRoute._addFileChildren(StoresRouteChildren)

interface TcgManagerRouteChildren {
  TcgManagerAnalyticsRoute: typeof TcgManagerAnalyticsRoute
  TcgManagerApprovedRoute: typeof TcgManagerApprovedRoute
  TcgManagerCalendarRoute: typeof TcgManagerCalendarRoute
  TcgManagerHistoryRoute: typeof TcgManagerHistoryRoute
  TcgManagerMyHistoryRoute: typeof TcgManagerMyHistoryRoute
  TcgManagerStoresRoute: typeof TcgManagerStoresRoute
  TcgManagerTournamentsPanelRoute: typeof TcgManagerTournamentsPanelRoute
  TcgManagerUploadRoute: typeof TcgManagerUploadRoute
  TcgManagerIndexRoute: typeof TcgManagerIndexRoute
  TcgManagerTournamentsIdRoute: typeof TcgManagerTournamentsIdRoute
}

const TcgManagerRouteChildren: TcgManagerRouteChildren = {
  TcgManagerAnalyticsRoute: TcgManagerAnalyticsRoute,
  TcgManagerApprovedRoute: TcgManagerApprovedRoute,
  TcgManagerCalendarRoute: TcgManagerCalendarRoute,
  TcgManagerHistoryRoute: TcgManagerHistoryRoute,
  TcgManagerMyHistoryRoute: TcgManagerMyHistoryRoute,
  TcgManagerStoresRoute: TcgManagerStoresRoute,
  TcgManagerTournamentsPanelRoute: TcgManagerTournamentsPanelRoute,
  TcgManagerUploadRoute: TcgManagerUploadRoute,
  TcgManagerIndexRoute: TcgManagerIndexRoute,
  TcgManagerTournamentsIdRoute: TcgManagerTournamentsIdRoute,
}

const TcgManagerRouteWithChildren = TcgManagerRoute._addFileChildren(
  TcgManagerRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CalendarRoute: CalendarRoute,
  CheckInboxRoute: CheckInboxRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  MetaRoute: MetaRoute,
  MyStatsRoute: MyStatsRoute,
  OrganizerRoute: OrganizerRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
  SessionsRoute: SessionsRouteWithChildren,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  StoresRoute: StoresRouteWithChildren,
  TcgManagerRoute: TcgManagerRouteWithChildren,
  DocsFeaturesRoute: DocsFeaturesRoute,
  PlayersPlayerTagRoute: PlayersPlayerTagRoute,
  TournamentsIdRoute: TournamentsIdRoute,
  PlayersPlayerTagAchievementsRoute: PlayersPlayerTagAchievementsRoute,
  PlayersPlayerTagSeasonSeasonIdRoute: PlayersPlayerTagSeasonSeasonIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
